name: 'Run rubocop-linter'
description: 'Run rubocop to improve code review experience.'
author: 'vinccool96'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  rubocop_version:
    description: 'Rubocop version'
  rubocop_extensions:
    description: 'Rubocop extensions'
    default: ''
  rubocop_flags:
    description: 'Rubocop flags. (rubocop <rubocop_flags>)'
    default: ''
  fail_level:
    description: 'The fail level of Rubocop. Default "error"'
    default: 'error'
  fail_on_error:
    description: |
      Exit code for rubocop when errors are found [true,false]
      Default is `false`.
    default: 'false'
  workdir:
    description: "The directory from which to look for and run Rubocop. Default '.'"
    default: '.'
  skip_install:
    description: "Do not install Rubocop or its extensions. Default: `false`"
    default: 'false'
  use_bundler:
    description: "Run Rubocop with bundle exec. Default: `false`"
    default: 'false'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_RUBOCOP_VERSION: ${{ inputs.rubocop_version }}
        INPUT_RUBOCOP_EXTENSIONS: ${{ inputs.rubocop_extensions }}
        INPUT_RUBOCOP_FLAGS: ${{ inputs.rubocop_flags }}
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_SKIP_INSTALL: ${{ inputs.skip_install }}
        INPUT_USE_BUNDLER: ${{ inputs.use_bundler }}
branding:
  icon: 'check-circle'
  color: 'red'